
name: Security Scan

on:
  push:
    branches:
      - '*'

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      
      - name: Install dependencies
        run: npm install  
        
      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@0.20.0
        with:
            scan-type: 'fs'
            scan-ref: 'package-lock.json'
      - name: Run Trivy SAST 
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'  # Modo de escaneamento do sistema de arquivos
          scan-ref: './'  # Diretório de escaneamento (normalmente, a raiz do repositório)
          scanners: 'secret,misconfig,license'  # Especificando os scanners a serem usados
          args: '--debug'  # Adicionando a flag de depuração para maior verbosidade